FROM node:17.0.1 AS builder

ARG SERVICE_NAME

WORKDIR /app

ADD *.json ./
ADD ./prisma ./prisma
ADD ./packages/$SERVICE_NAME ./packages/$SERVICE_NAME

RUN npm ci \
    && npm run build:project


FROM nginx:1.17.3-alpine 

ARG SERVICE_NAME
COPY --from=builder app/packages/${SERVICE_NAME}/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder app/packages/${SERVICE_NAME}/build /usr/share/nginx/html
