version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
    networks:
      - common-network

  backend:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
      context: '.'
      args:
        SERVICE_NAME: 'api'
    environment:
      JWT_SECRET: '${JWT_SECRET}'
      DATABASE_URL: 'mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}'
    ports:
      - '5000:5000'
    networks:
      - common-network

  cron:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
      context: '.'
      args:
        SERVICE_NAME: 'cron-tasks'
    environment:
      DATABASE_URL: 'mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}'
    networks:
      - common-network

  admin:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile.Nginx
      context: '.'
      args:
        SERVICE_NAME: 'admin'
    ports:
       - '3000:80'
    networks:
      - common-network
networks:
  common-network:
    driver: bridge

volumes:
  db_data:
